<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/register.css">
    <title>Document</title>
</head>
<body>
<div class="text">REJESTRACJA</div>
<form class="input" action="">
    <input type="email" name="email" placeholder="E-mail">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Zarejestruj"/>
</form>
</body>
</html>
